body:
  - type: textarea
    attributes:
      label: Goals
      description: What should this feature achieve?
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Background
      description: Why is this needed? Are there current alternatives or workarounds?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: How should this work? Are you interested in contributing?
    validations:
      required: true
