/**
 * @license
 * Copyright (c) ZesTest 2025-2030. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file may contain AI-assisted code.
 * See LICENSE and NOTICE files for details.
 */

/**
 * Keyboard handlers and display helpers for the `praman inspect` CLI command.
 *
 * @remarks
 * Each keyboard handler is a focused function invoked via the dispatch
 * table in {@link dispatchInspectorKey}. Separating handlers from the
 * main orchestrator keeps cognitive complexity within the 15-limit.
 *
 * @module cli/inspect-commands
 */

import { execSync } from 'node:child_process';
import process from 'node:process';

import type { Page } from '@playwright/test';

import { logDivider, logError, logRaw, logSuccess, logWarn } from './logger.js';

import { createControlTreeScript } from '#bridge/browser-scripts/control-tree.js';
import { injectBridge } from '#bridge/injection.js';

// ── Types ─────────────────────────────────────────────────────────────────────

/** Metadata shape returned by the browser-side inspect script. */
export interface ControlMetaResult {
  readonly id: string;
  readonly controlType: string;
  readonly visible: boolean;
  readonly enabled: boolean;
  readonly domId: string | null;
  readonly properties: Readonly<Record<string, string | number | boolean | null>>;
  readonly aggregationNames: readonly string[];
  readonly bindingPaths: Readonly<Record<string, string>>;
}

/** Shared mutable inspector state threaded through keyboard handlers. */
export interface InspectorState {
  lastMeta: ControlMetaResult | null;
  lastSelectors: readonly string[];
}

// ── Constants ─────────────────────────────────────────────────────────────────

/** Property names checked (in order) when building stable selectors. */
const SELECTOR_PROPS = ['text', 'title', 'label', 'value', 'placeholder', 'key'] as const;

const RANKING_SYMBOLS = ['①', '②', '③', '④', '⑤'] as const;

const NO_CONTROL_MSG = 'No control inspected yet — click an element first';

// ── Public Helpers ────────────────────────────────────────────────────────────

/**
 * Parses a `WIDTHxHEIGHT` viewport string into a `{ width, height }` object.
 *
 * @param viewport - Viewport string such as `1440x900`.
 * @returns Parsed dimensions or `{ width: 1920, height: 1080 }` on error.
 *
 * @example
 * ```typescript
 * parseViewport('1440x900'); // { width: 1440, height: 900 }
 * ```
 */
export function parseViewport(viewport: string): { width: number; height: number } {
  const parts = viewport.split('x');
  const first = parts[0];
  const second = parts[1];
  const width = first !== undefined ? Number.parseInt(first, 10) : Number.NaN;
  const height = second !== undefined ? Number.parseInt(second, 10) : Number.NaN;
  if (!Number.isNaN(width) && !Number.isNaN(height) && width > 0 && height > 0) {
    return { width, height };
  }
  return { width: 1920, height: 1080 };
}

/**
 * Copies text to the system clipboard using platform-appropriate tools.
 *
 * @param text - The text to place on the clipboard.
 *
 * @example
 * ```typescript
 * copyToClipboard("ui5=sap.m.Button[text='Save']");
 * ```
 */
function copyToClipboard(text: string): void {
  try {
    const safe = text.replaceAll("'", "'\\''");
    if (process.platform === 'darwin') {
      // eslint-disable-next-line sonarjs/os-command -- Safe: value is a pre-escaped selector string generated by buildSelectors
      execSync(`printf '%s' '${safe}' | pbcopy`);
    } else if (process.platform === 'win32') {
      // eslint-disable-next-line sonarjs/os-command -- Safe: value is a pre-escaped selector string generated by buildSelectors
      execSync(`echo ${text} | clip`, { shell: 'cmd.exe' });
    } else {
      // eslint-disable-next-line sonarjs/os-command -- Safe: value is a pre-escaped selector string generated by buildSelectors
      execSync(
        `printf '%s' '${safe}' | xclip -selection clipboard 2>/dev/null || printf '%s' '${safe}' | xsel --clipboard --input`,
      );
    }
    logSuccess('Copied to clipboard');
  } catch {
    logWarn('Clipboard copy unavailable — paste from terminal output above');
  }
}

// ── Selector Builder ──────────────────────────────────────────────────────────

function getStringProp(
  properties: Readonly<Record<string, string | number | boolean | null>>,
  key: string,
): string | undefined {
  // eslint-disable-next-line security/detect-object-injection -- key comes from compile-time SELECTOR_PROPS constant
  const val = properties[key];
  if (typeof val === 'string' && val.length > 0) {
    return val;
  }
  return undefined;
}

function buildFixtureProps(meta: ControlMetaResult): string {
  const pairs: string[] = [];
  for (const [k, v] of Object.entries(meta.properties)) {
    if (typeof v === 'string' && v.length > 0) {
      pairs.push(`${k}: '${v}'`);
      if (pairs.length >= 2) break;
    }
  }
  return pairs.join(', ');
}

/**
 * Generates selector candidates for a control, ranked best to worst.
 *
 * @param meta - The full control metadata from the bridge.
 * @returns Array of `ui5=...` selector strings, highest stability first.
 *
 * @example
 * ```typescript
 * const selectors = buildSelectors(meta);
 * // ['ui5=sap.m.Button[text=Save]', 'ui5=sap.m.Button#saveBtn']
 * ```
 */
export function buildSelectors(meta: ControlMetaResult): readonly string[] {
  const type = meta.controlType;
  const candidates: string[] = [];

  for (const prop of SELECTOR_PROPS) {
    const val = getStringProp(meta.properties, prop);
    if (val !== undefined) {
      candidates.push(`ui5=${type}[${prop}=${val}]`);
      break;
    }
  }

  if (meta.id.length > 0 && !meta.id.startsWith('__')) {
    candidates.push(`ui5=${type}#${meta.id}`);
  }

  const propPairs = Object.entries(meta.properties)
    .filter(
      (entry): entry is [string, string] => typeof entry[1] === 'string' && entry[1].length > 0,
    )
    .slice(0, 2);

  if (propPairs.length >= 2) {
    const combo = propPairs.map(([k, v]) => `[${k}=${v}]`).join('');
    const candidate = `ui5=${type}${combo}`;
    if (!candidates.includes(candidate)) {
      candidates.push(candidate);
    }
  }

  if (candidates.length === 0) {
    candidates.push(`ui5=${type}`);
  }
  return candidates;
}

// ── Display Functions ─────────────────────────────────────────────────────────

function formatRank(index: number): string {
  if (index < RANKING_SYMBOLS.length) {
    // eslint-disable-next-line security/detect-object-injection -- index is a bounded loop counter
    const symbol = RANKING_SYMBOLS[index];
    return symbol ?? String(index + 1);
  }
  return String(index + 1);
}

function printSelectorList(selectors: readonly string[]): void {
  for (const [i, sel] of selectors.entries()) {
    logRaw(`  ${formatRank(i)}  ${sel}`);
  }
  logRaw('');
}

/** Prints the full control inspection report. */
export function printReport(meta: ControlMetaResult, selectors: readonly string[]): void {
  logDivider(`Clicked: ${meta.controlType}`);
  logRaw('');
  logRaw(`  ID:      ${meta.id}`);
  logRaw(`  Type:    ${meta.controlType}`);
  logRaw(`  Visible: ${String(meta.visible)}  Enabled: ${String(meta.enabled)}`);

  const propEntries = Object.entries(meta.properties).filter(([, v]) => v !== null);
  if (propEntries.length > 0) {
    logRaw('\n  Properties:');
    for (const [key, val] of propEntries.slice(0, 10)) {
      logRaw(`    ${key} = ${JSON.stringify(val)}`);
    }
  }

  const bindEntries = Object.entries(meta.bindingPaths);
  if (bindEntries.length > 0) {
    logRaw('\n  Bindings:');
    for (const [prop, path] of bindEntries) {
      logRaw(`    ${prop} → {${path}}`);
    }
  }

  logDivider('Selectors (best → worst)');
  logRaw('');
  printSelectorList(selectors);

  const best = selectors[0] ?? `ui5=${meta.controlType}`;
  const fixtureProps = buildFixtureProps(meta);
  const propsSuffix = fixtureProps.length > 0 ? `, properties: { ${fixtureProps} }` : '';

  logRaw('  Fixture:');
  logRaw(`    await ui5.control({ controlType: '${meta.controlType}'${propsSuffix} });`);
  logRaw('\n  Locator:');
  logRaw(`    page.locator("${best}")`);
  logRaw('');
}

/** Prints the keyboard shortcut help. */
function printHelp(): void {
  logDivider('Keyboard Shortcuts');
  logRaw('');
  logRaw('  t   Show full UI5 control tree');
  logRaw('  s   Re-print selectors for last clicked control');
  logRaw('  c   Copy best selector to clipboard');
  logRaw('  f   Copy fixture code to clipboard');
  logRaw('  l   Copy locator code to clipboard');
  logRaw('  b   Show binding paths for last clicked control');
  logRaw('  r   Re-inject bridge (after page navigation)');
  logRaw('  h   Show this help');
  logRaw('  q   Quit inspector');
  logRaw('');
}

// ── Key Command Handlers ──────────────────────────────────────────────────────

async function handleTreeKey(page: Page): Promise<void> {
  try {
    const snapshot = await page.evaluate(
      createControlTreeScript({ maxDepth: 6, maxControls: 2000 }),
    );
    logDivider('Control Tree');
    logRaw(JSON.stringify(snapshot, null, 2));
  } catch (err: unknown) {
    logError(`Tree failed: ${err instanceof Error ? err.message : String(err)}`);
  }
}

async function handleReInjectBridge(page: Page): Promise<void> {
  try {
    await injectBridge(page);
    logSuccess('Bridge re-injected');
  } catch (err: unknown) {
    logError(`Re-inject failed: ${err instanceof Error ? err.message : String(err)}`);
  }
}

function handleSelectorsKey(state: InspectorState): void {
  if (state.lastMeta === null || state.lastSelectors.length === 0) {
    logWarn(NO_CONTROL_MSG);
    return;
  }
  logDivider('Selectors');
  printSelectorList(state.lastSelectors);
}

function handleBindingsKey(state: InspectorState): void {
  if (state.lastMeta === null) {
    logWarn(NO_CONTROL_MSG);
    return;
  }
  logDivider(`Bindings: ${state.lastMeta.controlType}`);
  const entries = Object.entries(state.lastMeta.bindingPaths);
  if (entries.length === 0) {
    logRaw('  (no bindings found)');
  } else {
    for (const [prop, path] of entries) {
      logRaw(`  ${prop}  →  {${path}}`);
    }
  }
  logRaw('');
}

function handleCopyKey(state: InspectorState): void {
  const best = state.lastSelectors[0];
  if (best === undefined) {
    logWarn(NO_CONTROL_MSG);
    return;
  }
  copyToClipboard(best);
  logRaw(`  ${best}`);
}

function handleFixtureKey(state: InspectorState): void {
  if (state.lastMeta === null) {
    logWarn(NO_CONTROL_MSG);
    return;
  }
  const fixtureProps = buildFixtureProps(state.lastMeta);
  const propsSuffix = fixtureProps.length > 0 ? `, properties: { ${fixtureProps} }` : '';
  const code = `await ui5.control({ controlType: '${state.lastMeta.controlType}'${propsSuffix} });`;
  copyToClipboard(code);
  logRaw(`  ${code}`);
}

function handleLocatorKey(state: InspectorState): void {
  const best =
    state.lastSelectors[0] ?? (state.lastMeta !== null ? `ui5=${state.lastMeta.controlType}` : '');
  if (best.length === 0) {
    logWarn(NO_CONTROL_MSG);
    return;
  }
  const code = `page.locator("${best}")`;
  copyToClipboard(code);
  logRaw(`  ${code}`);
}

// ── Dispatch ──────────────────────────────────────────────────────────────────

/**
 * Dispatches a keypress to the appropriate inspector command handler.
 *
 * @param key - The raw key string from stdin.
 * @param page - The currently active Playwright page, or `undefined`.
 * @param state - Shared mutable inspector state.
 * @param resolve - Callback to resolve the inspector's lifecycle promise (quit).
 *
 * @example
 * ```typescript
 * process.stdin.on('data', (key: string) => {
 *   dispatchInspectorKey(key, page, state, resolve);
 * });
 * ```
 */
export function dispatchInspectorKey(
  key: string,
  page: Page | undefined,
  state: InspectorState,
  resolve: () => void,
): void {
  if (key === 'q' || key === '\u0003') {
    resolve();
    return;
  }
  if (page === undefined) {
    return;
  }

  switch (key) {
    case 'h': {
      printHelp();
      break;
    }
    case 's': {
      handleSelectorsKey(state);
      break;
    }
    case 'b': {
      handleBindingsKey(state);
      break;
    }
    case 'c': {
      handleCopyKey(state);
      break;
    }
    case 'f': {
      handleFixtureKey(state);
      break;
    }
    case 'l': {
      handleLocatorKey(state);
      break;
    }
    case 't': {
      void handleTreeKey(page);
      break;
    }
    case 'r': {
      void handleReInjectBridge(page);
      break;
    }
    default:
      break;
  }
}
