import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // ── Documentation sidebar (Menu 1) ──
  // New doc pages will appear here automatically as they are created.
  // Add explicit entries when you want to control ordering.
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [{ type: 'autogenerated', dirName: 'examples' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    'changelog',
    'security',
  ],

  // ── API Reference sidebar (Menu 2) — auto-generated by docusaurus-plugin-typedoc ──
  // TypeDoc generates markdown into docs/api/ at build time.
  // No manual entries needed — all API pages appear automatically.
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
